name: CI

on: 
  push:
    branches:
      - main

jobs:

  unit-test:
    #needs: formatter
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install .
      - name: Test with pytest
        env: 
          XERO_ID: ${{ secrets.XERO_ID }}
          XERO_SECRET: ${{ secrets.XERO_SECRET }}
        run: pytest --cov .
        